#!/usr/bin/env bash
#
# Run all dotfiles installers.

DOTFILES_ROOT="`pwd`"

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find $DOTFILES_ROOT -name install.sh | while read installer ; do sh -c "${installer}" ; done
